"""Every adapter in the registry must pass this suite — written before the
real adapters landed (M5), per docs/implementation-plan.md "Adapter
registry and conformance". Parametrized over the registry itself, so a new
entry in adapters/registry.py is covered automatically with no edit here.

The audio is a real corpus clip with a known transcript, not synthetic
silence. That costs a couple of seconds per adapter and buys two things a
zeros-buffer cannot: proof that the adapter's model actually runs and
produces text, and a state-isolation check that means something (silence
transcribes to "" on every real model, so "session 1's text differs from
session 2's" would hold vacuously).

Idempotent replay (pushing the same seq range twice is a no-op) is
deliberately NOT tested here: that property is implemented in server.py's
last_seq_applied check, not inside any individual adapter — see
test_server.py::test_push_idempotent_replay.
"""

from __future__ import annotations

import wave
from pathlib import Path

import pytest

from adapters import weights
from adapters.base import NotSupported
from adapters.registry import _REGISTRY, NEEDS_WEIGHTS, build

ADAPTER_NAMES = sorted(_REGISTRY.keys())
CORPUS_DIR = Path(__file__).resolve().parents[2] / "corpus" / "large"


def _first_clip() -> Path | None:
    """The large corpus (10-20s utterances), generated by
    scripts/gen_corpus_large.py. It is git-ignored, so a fresh checkout
    has none and the clip-dependent tests skip with an actionable reason
    rather than failing."""
    clips = sorted(CORPUS_DIR.rglob("*.wav"))  # one subdirectory per clip kind
    return clips[0] if clips else None


@pytest.fixture(scope="session")
def speech() -> bytes:
    """Raw s16le PCM from a corpus clip — the same opaque payload shape a
    real push carries (docs/PROTOCOL.md)."""
    clip = _first_clip()
    if clip is None:
        pytest.skip(f"no clips in {CORPUS_DIR} — run scripts/gen_corpus_large.py")
    with wave.open(str(clip)) as w:
        assert (w.getframerate(), w.getnchannels(), w.getsampwidth()) == (16000, 1, 2)
        return w.readframes(w.getnframes())


@pytest.fixture(scope="module")
def _built():
    """One adapter instance per name for the whole module: constructing a
    real adapter loads its weights (~0.3s, and 130MB for the CTC model), and
    doing that once per test would dominate the suite's runtime for no
    added coverage. Every test below treats its adapter as read-only apart
    from the session states it creates, which is the isolation property
    being tested anyway."""
    return {}


@pytest.fixture
def adapter(request, _built):
    name = request.getfixturevalue("name")
    if name in NEEDS_WEIGHTS and not weights.available():
        pytest.skip(f"{name}: no model weights on disk — run models/fetch.sh")
    if name not in _built:
        _built[name] = build(name)
    return _built[name]


@pytest.mark.parametrize("name", ADAPTER_NAMES)
class TestAdapterConformance:
    def test_compatibility_key_is_stable_across_calls(self, adapter, name):
        k1, k2 = adapter.compatibility_key(), adapter.compatibility_key()
        assert k1 == k2
        assert k1.hash() == k2.hash()

    def test_state_is_isolated_between_sessions(self, adapter, name, speech):
        s1 = adapter.create_state("session-1")
        s2 = adapter.create_state("session-2")
        assert s1 is not s2

        _, s1 = adapter.infer(speech, s1)
        d1 = adapter.finalize(s1)
        d2 = adapter.finalize(s2)  # must reflect s2's own (empty) history, not s1's

        assert d1.text, "an adapter that saw a whole spoken sentence produced no text at all"
        assert d1.text != d2.text, "mutating one session's state affected another's"

    def test_finalize_after_infer(self, adapter, name, speech):
        st = adapter.create_state("s1")
        _, st = adapter.infer(speech, st)
        delta = adapter.finalize(st)
        assert isinstance(delta.text, str)

    def test_state_survives_a_second_utterance(self, adapter, name, speech):
        """A session outlives an utterance (M2's utterance lifecycle), so
        finalize must leave the state usable rather than spent. On the
        streaming adapters this is load-bearing: sherpa-onnx's
        input_finished() is terminal for a stream, so without
        sherpa_online's roll-the-stream step the SECOND utterance of every
        real session would fail while every mock test kept passing."""
        st = adapter.create_state("s1")
        _, st = adapter.infer(speech, st)
        first = adapter.finalize(st)
        _, st = adapter.infer(speech, st)
        second = adapter.finalize(st)
        assert first.text and second.text

    def test_finalize_with_no_audio_is_safe(self, adapter, name):
        """An utterance can end having buffered nothing (a session closed
        during silence). This must return empty text, not raise and not
        take the process down — sherpa-onnx's Whisper recognizer SIGSEGVs
        on a zero-length buffer, which is why buffered.MIN_UTTERANCE_S
        exists. A crash here kills the pytest process outright, so the
        failure is unmissable."""
        st = adapter.create_state("s1")
        assert isinstance(adapter.finalize(st).text, str)

    def test_serializable_flag_is_honest(self, adapter, name):
        """Capabilities.serializable must match what serialize/deserialize
        actually do — a real adapter that declares False must raise
        NotSupported, never silently no-op or fake a checkpoint."""
        caps = adapter.capabilities()
        st = adapter.create_state("s1")

        if caps.serializable:
            blob = adapter.serialize(st)
            assert isinstance(blob, (bytes, bytearray))
            assert adapter.deserialize(blob) is not None
        else:
            with pytest.raises(NotSupported):
                adapter.serialize(st)
            with pytest.raises(NotSupported):
                adapter.deserialize(b"")

    def test_capabilities_are_well_formed(self, adapter, name):
        caps = adapter.capabilities()
        assert caps.modes, "an adapter must declare at least one supported mode"
        assert caps.modes <= {"online", "offline"}
        assert caps.min_chunk_ms <= caps.max_chunk_ms
        if not caps.streaming:
            assert "online" not in caps.modes, (
                "a non-streaming adapter cannot serve online partials — "
                "the router (M6) filters on exactly this"
            )


@pytest.mark.skipif(not weights.available(), reason="no model weights on disk — run models/fetch.sh")
def test_every_registered_adapter_owns_a_kv_cache():
    """The fleet's defining property, asserted so it cannot regress.

    Every deployed adapter drives its model's ONNX graphs directly and owns
    the state tensors, so all of them can checkpoint. The sherpa-wrapped
    adapters and the mock moved to deprecated_experiments/ once that was
    true of every worker: they could only ever exercise the degradation
    path, and an adapter that silently reappeared claiming
    serializable=False would make `checkpoint_degraded_total` ambiguous
    again — is this a cross-model failover, or a worker that simply cannot
    checkpoint?
    """
    for name in sorted(_REGISTRY):
        caps = build(name).capabilities()
        assert caps.serializable, f"{name} cannot checkpoint — every deployed adapter must"


def test_the_three_families_have_distinct_compatibility_keys():
    """Three models, three keys. Cross-family failover is only meaningful
    if the keys actually differ, and same-family restore is only safe if
    replicas actually match — both are this one assertion."""
    keys = {name: build(name).compatibility_key().hash() for name in sorted(_REGISTRY)}
    assert len(set(keys.values())) == len(keys), f"two adapters share a key: {keys}"


def test_whisper_is_offline_only_and_the_streaming_pair_is_not():
    """Capability, not preference. Whisper's encoder consumes a fixed 30s
    window, so `router.Pick` must filter it out of every online session —
    that filter is the only thing keeping live traffic off it."""
    assert not build("whisper_kv").capabilities().streaming
    assert build("whisper_kv").capabilities().modes == frozenset({"offline"})
    for name in ("zipformer_kv", "conformer_ctc_kv"):
        assert build(name).capabilities().streaming, f"{name} must serve online sessions"
