// Package corpus reads the committed corpus/*.wav clips (see
// corpus/README.md) into raw PCM. Used by cmd/smoketest now and by
// cmd/loadgen from M7 — written once, here, so the two don't grow two
// independent WAV readers.
package corpus

import (
	"encoding/binary"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Clip is one loaded WAV file's format plus its raw PCM payload.
type Clip struct {
	SampleRateHz  int
	Channels      int
	BitsPerSample int
	PCM           []byte // raw samples, exactly as stored in the file's data chunk
}

// LoadWAV reads a canonical PCM WAV file (RIFF/WAVE, walking chunks
// rather than assuming a fixed 44-byte header — macOS `say -o
// --file-format=WAVE` produces this shape, but nothing here assumes a
// specific chunk order beyond fmt appearing before data).
func LoadWAV(path string) (Clip, error) {
	f, err := os.Open(path)
	if err != nil {
		return Clip{}, err
	}
	defer f.Close()

	var riffHeader [12]byte
	if _, err := io.ReadFull(f, riffHeader[:]); err != nil {
		return Clip{}, fmt.Errorf("corpus: %s: read RIFF header: %w", path, err)
	}
	if string(riffHeader[0:4]) != "RIFF" || string(riffHeader[8:12]) != "WAVE" {
		return Clip{}, fmt.Errorf("corpus: %s: not a RIFF/WAVE file", path)
	}

	var clip Clip
	var haveFmt, haveData bool

	for {
		var chunkHeader [8]byte
		_, err := io.ReadFull(f, chunkHeader[:])
		if err == io.EOF {
			break
		}
		if err != nil {
			return Clip{}, fmt.Errorf("corpus: %s: read chunk header: %w", path, err)
		}
		chunkID := string(chunkHeader[0:4])
		chunkSize := binary.LittleEndian.Uint32(chunkHeader[4:8])

		switch chunkID {
		case "fmt ":
			body := make([]byte, chunkSize)
			if _, err := io.ReadFull(f, body); err != nil {
				return Clip{}, fmt.Errorf("corpus: %s: read fmt chunk: %w", path, err)
			}
			if len(body) < 16 {
				return Clip{}, fmt.Errorf("corpus: %s: fmt chunk too short", path)
			}
			audioFormat := binary.LittleEndian.Uint16(body[0:2])
			if audioFormat != 1 { // 1 == PCM
				return Clip{}, fmt.Errorf("corpus: %s: audio format %d is not PCM", path, audioFormat)
			}
			clip.Channels = int(binary.LittleEndian.Uint16(body[2:4]))
			clip.SampleRateHz = int(binary.LittleEndian.Uint32(body[4:8]))
			clip.BitsPerSample = int(binary.LittleEndian.Uint16(body[14:16]))
			haveFmt = true

		case "data":
			clip.PCM = make([]byte, chunkSize)
			if _, err := io.ReadFull(f, clip.PCM); err != nil {
				return Clip{}, fmt.Errorf("corpus: %s: read data chunk: %w", path, err)
			}
			haveData = true

		default:
			if _, err := f.Seek(int64(chunkSize), io.SeekCurrent); err != nil {
				return Clip{}, fmt.Errorf("corpus: %s: skip chunk %q: %w", path, chunkID, err)
			}
		}

		if chunkSize%2 == 1 { // RIFF chunks are word-aligned; skip the pad byte
			if _, err := f.Seek(1, io.SeekCurrent); err != nil {
				return Clip{}, err
			}
		}
	}

	if !haveFmt || !haveData {
		return Clip{}, fmt.Errorf("corpus: %s: missing fmt or data chunk", path)
	}
	return clip, nil
}

// --- corpus selection ---

// Dir is the corpus every load, benchmark and chaos path reads from.
//
// It is corpus/large — ~500 clips of 10-20s, generated by
// scripts/gen_corpus_large.py. The ten short clips in corpus/ are kept as
// the committed ground truth for protocol-level assertions, but they are
// 1-3s each and a single utterance apiece, which makes them useless for
// anything that measures behaviour at scale: an utterance-length chart
// built from them has no x-axis, replay-cost bounding is never stressed,
// and endpointing never sees a pause.
//
// corpus/large is git-ignored (it is ~240MB) and reproducible from a
// seed, so it has to be generated once per checkout. ResolveDir says so
// explicitly rather than letting a caller fail later with "no such file".
const Dir = "corpus/large"

// GenerateHint is the command that fixes a missing corpus. Named once so
// every entry point gives the same instruction.
const GenerateHint = "scripts/gen_corpus_large.py"

// WalkClips returns every .wav under root, sorted. The corpus is laid out
// one subdirectory per KIND (monologue/, dialogue/, long_form/, ...), so a
// flat glob would silently find nothing — which is a much worse failure
// than an error, since it presents as "corpus is empty" on a corpus that
// is full.
func WalkClips(root string) ([]string, error) {
	var paths []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.EqualFold(filepath.Ext(p), ".wav") {
			paths = append(paths, p)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)
	return paths, nil
}

// ResolveDir finds Dir by walking up from the working directory, so a
// caller works from the repo root or from a package subdirectory (where
// `go test` runs). Returns an actionable error rather than a path that
// does not exist.
func ResolveDir() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; {
		candidate := filepath.Join(dir, Dir)
		if clips, err := WalkClips(candidate); err == nil && len(clips) > 0 {
			return candidate, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("corpus: no clips found under %s (searched upward from %s) — run %s to generate it; it is git-ignored, so a fresh checkout has none",
		Dir, wd, GenerateHint)
}

// Clips lists every WAV in the resolved corpus, sorted, so a given --seed
// maps to the same clips across runs and machines.
func Clips() ([]string, error) {
	dir, err := ResolveDir()
	if err != nil {
		return nil, err
	}
	return WalkClips(dir)
}

// AnyClip returns one clip from the corpus — the default for tools that
// stream a single utterance (cmd/smoketest, cmd/chaostest) and do not care
// which one, only that it is real speech of a realistic length.
func AnyClip() (string, error) {
	paths, err := Clips()
	if err != nil {
		return "", err
	}
	return paths[0], nil
}
